#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"; ENV_FILE="$ROOT_DIR/.env"; API_DIR="$ROOT_DIR/backend"; UI_DIR="$ROOT_DIR/frontend"; MIGRATION_DIR="$API_DIR/migrations"
read_env() { awk -F= -v key="$1" '$0 !~ /^[[:space:]]*#/ && $1 == key { value=substr($0,index($0,"=")+1); gsub(/^[[:space:]]+|[[:space:]]+$/, "", value); gsub(/^["\047]|["\047]$/, "", value); print value; exit }' "$ENV_FILE"; }
load_env_key() { local key="$1" parsed; [ -n "${!key-}" ] && return 0; [ -f "$ENV_FILE" ] || return 0; parsed="$(read_env "$key")"; [ -z "$parsed" ] || export "$key=$parsed"; }
for key in DATABASE_URL JWT_SECRET GOVERNANCE_TENANT_ID OPENROUTER_API_KEY OPENROUTER_MODEL OPENROUTER_BASE_URL ALLOW_SCHEMA_MIGRATION BACKEND_PORT FRONTEND_PORT CLIENT_URL; do load_env_key "$key"; done
BACKEND_PORT="${BACKEND_PORT:-${PORT:-3001}}"; FRONTEND_PORT="${FRONTEND_PORT:-5173}"
export BACKEND_PORT FRONTEND_PORT
export CLIENT_URL="${CLIENT_URL:-http://127.0.0.1:${FRONTEND_PORT}}"
fail() { printf 'error: %s\n' "$*" >&2; exit 1; }
check_config() { local jwt_secret="${JWT_SECRET:-}"; command -v node >/dev/null || fail "node is required"; command -v npm >/dev/null || fail "npm is required"; [ -n "${DATABASE_URL:-}" ] || fail "DATABASE_URL is required"; [ -n "${GOVERNANCE_TENANT_ID:-}" ] || fail "GOVERNANCE_TENANT_ID is required"; [ "${#jwt_secret}" -ge 32 ] || fail "JWT_SECRET must contain at least 32 characters"; case "$DATABASE_URL" in *example*|*changeme*|*password@*) fail "DATABASE_URL contains a placeholder" ;; esac; printf 'configuration valid for tenant %s\n' "$GOVERNANCE_TENANT_ID"; }
migrate() { check_config; [ "${ALLOW_SCHEMA_MIGRATION:-0}" = "1" ] || fail "set ALLOW_SCHEMA_MIGRATION=1 for the explicit migration command"; command -v psql >/dev/null || fail "psql is required for migrations"; local found=0; for migration in "$MIGRATION_DIR"/*.sql; do [ -f "$migration" ] || continue; found=1; psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f "$migration"; done; [ "$found" = "1" ] || fail "no migrations found"; }
start_services() { check_config; [ -d "$API_DIR/node_modules" ] || fail "backend dependencies are missing; install them explicitly"; [ -d "$UI_DIR/node_modules" ] || fail "frontend dependencies are missing; install them explicitly"; (cd "$API_DIR" && PORT="$BACKEND_PORT" BACKEND_PORT="$BACKEND_PORT" node server.js) & api_pid=$!; ui_pid=""; trap 'kill "$api_pid" ${ui_pid:+"$ui_pid"} 2>/dev/null || true; wait "$api_pid" ${ui_pid:+"$ui_pid"} 2>/dev/null || true' INT TERM EXIT; local api_ready=false; for _ in {1..120}; do if curl --fail --silent --max-time 1 "http://127.0.0.1:${BACKEND_PORT}/api/health" >/dev/null 2>&1; then api_ready=true; break; fi; kill -0 "$api_pid" 2>/dev/null || break; sleep 0.25; done; [ "$api_ready" = true ] || fail "backend failed to become ready on port $BACKEND_PORT"; (cd "$UI_DIR" && BACKEND_PORT="$BACKEND_PORT" FRONTEND_PORT="$FRONTEND_PORT" npm run dev -- --host 127.0.0.1 --port "$FRONTEND_PORT") & ui_pid=$!; wait "$api_pid" "$ui_pid"; }
case "${1:-start}" in check) check_config ;; migrate) migrate ;; start) start_services ;; *) fail "usage: $0 {check|migrate|start}" ;; esac
